DROP DATABASE IF EXISTS foodi;
CREATE DATABASE foodi;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  userName VARCHAR UNIQUE NOT NULL,
  email VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL,
  firstName VARCHAR NOT NULL,
  lastName VARCHAR NOT NULL, 
  location VARCHAR NOT NULL, 
);

CREATE TABLE cities (
  id SERIAL PRIMARY KEY,
  name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE restaurants (
  id SERIAL PRIMARY KEY,
  name VARCHAR UNIQUE NOT NULL,
  hometown_id INT REFERENCES cities (id) NOT NULL,
);